server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lianxi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #   url:jdbc:mysql://58.87.85.198/lianxi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:



mybatis-plus:
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.hbj.myelitis.pojo

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
